package android.support.constraint;

public final class R {
    private R() {
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets = 2130968631;
        public static final int barrierDirection = 2130968632;
        public static final int chainUseRtl = 2130968674;
        public static final int constraintSet = 2130968726;
        public static final int constraint_referenced_ids = 2130968727;
        public static final int content = 2130968728;
        public static final int emptyVisibility = 2130968767;
        public static final int layout_constrainedHeight = 2130968872;
        public static final int layout_constrainedWidth = 2130968873;
        public static final int layout_constraintBaseline_creator = 2130968874;
        public static final int layout_constraintBaseline_toBaselineOf = 2130968875;
        public static final int layout_constraintBottom_creator = 2130968876;
        public static final int layout_constraintBottom_toBottomOf = 2130968877;
        public static final int layout_constraintBottom_toTopOf = 2130968878;
        public static final int layout_constraintCircle = 2130968879;
        public static final int layout_constraintCircleAngle = 2130968880;
        public static final int layout_constraintCircleRadius = 2130968881;
        public static final int layout_constraintDimensionRatio = 2130968882;
        public static final int layout_constraintEnd_toEndOf = 2130968883;
        public static final int layout_constraintEnd_toStartOf = 2130968884;
        public static final int layout_constraintGuide_begin = 2130968885;
        public static final int layout_constraintGuide_end = 2130968886;
        public static final int layout_constraintGuide_percent = 2130968887;
        public static final int layout_constraintHeight_default = 2130968888;
        public static final int layout_constraintHeight_max = 2130968889;
        public static final int layout_constraintHeight_min = 2130968890;
        public static final int layout_constraintHeight_percent = 2130968891;
        public static final int layout_constraintHorizontal_bias = 2130968892;
        public static final int layout_constraintHorizontal_chainStyle = 2130968893;
        public static final int layout_constraintHorizontal_weight = 2130968894;
        public static final int layout_constraintLeft_creator = 2130968895;
        public static final int layout_constraintLeft_toLeftOf = 2130968896;
        public static final int layout_constraintLeft_toRightOf = 2130968897;
        public static final int layout_constraintRight_creator = 2130968898;
        public static final int layout_constraintRight_toLeftOf = 2130968899;
        public static final int layout_constraintRight_toRightOf = 2130968900;
        public static final int layout_constraintStart_toEndOf = 2130968901;
        public static final int layout_constraintStart_toStartOf = 2130968902;
        public static final int layout_constraintTop_creator = 2130968903;
        public static final int layout_constraintTop_toBottomOf = 2130968904;
        public static final int layout_constraintTop_toTopOf = 2130968905;
        public static final int layout_constraintVertical_bias = 2130968906;
        public static final int layout_constraintVertical_chainStyle = 2130968907;
        public static final int layout_constraintVertical_weight = 2130968908;
        public static final int layout_constraintWidth_default = 2130968909;
        public static final int layout_constraintWidth_max = 2130968910;
        public static final int layout_constraintWidth_min = 2130968911;
        public static final int layout_constraintWidth_percent = 2130968912;
        public static final int layout_editor_absoluteX = 2130968914;
        public static final int layout_editor_absoluteY = 2130968915;
        public static final int layout_goneMarginBottom = 2130968916;
        public static final int layout_goneMarginEnd = 2130968917;
        public static final int layout_goneMarginLeft = 2130968918;
        public static final int layout_goneMarginRight = 2130968919;
        public static final int layout_goneMarginStart = 2130968920;
        public static final int layout_goneMarginTop = 2130968921;
        public static final int layout_optimizationLevel = 2130968924;

        private attr() {
        }
    }

    public static final class id {
        public static final int bottom = 2131296324;
        public static final int end = 2131296782;
        public static final int gone = 2131296800;
        public static final int invisible = 2131297160;
        public static final int left = 2131297167;
        public static final int packed = 2131297593;
        public static final int parent = 2131297595;
        public static final int percent = 2131297599;
        public static final int right = 2131297620;
        public static final int spread = 2131297674;
        public static final int spread_inside = 2131297675;
        public static final int start = 2131297681;
        public static final int top = 2131298417;
        public static final int wrap = 2131298445;

        private id() {
        }
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = {16842948, 16843039, 16843040, 16843071, 16843072, com.thecrackertechnology.andrax.R.attr.barrierAllowsGoneWidgets, com.thecrackertechnology.andrax.R.attr.barrierDirection, com.thecrackertechnology.andrax.R.attr.chainUseRtl, com.thecrackertechnology.andrax.R.attr.constraintSet, com.thecrackertechnology.andrax.R.attr.constraint_referenced_ids, com.thecrackertechnology.andrax.R.attr.layout_constrainedHeight, com.thecrackertechnology.andrax.R.attr.layout_constrainedWidth, com.thecrackertechnology.andrax.R.attr.layout_constraintBaseline_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintBaseline_toBaselineOf, com.thecrackertechnology.andrax.R.attr.layout_constraintBottom_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintBottom_toBottomOf, com.thecrackertechnology.andrax.R.attr.layout_constraintBottom_toTopOf, com.thecrackertechnology.andrax.R.attr.layout_constraintCircle, com.thecrackertechnology.andrax.R.attr.layout_constraintCircleAngle, com.thecrackertechnology.andrax.R.attr.layout_constraintCircleRadius, com.thecrackertechnology.andrax.R.attr.layout_constraintDimensionRatio, com.thecrackertechnology.andrax.R.attr.layout_constraintEnd_toEndOf, com.thecrackertechnology.andrax.R.attr.layout_constraintEnd_toStartOf, com.thecrackertechnology.andrax.R.attr.layout_constraintGuide_begin, com.thecrackertechnology.andrax.R.attr.layout_constraintGuide_end, com.thecrackertechnology.andrax.R.attr.layout_constraintGuide_percent, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_default, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_max, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_min, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_percent, com.thecrackertechnology.andrax.R.attr.layout_constraintHorizontal_bias, com.thecrackertechnology.andrax.R.attr.layout_constraintHorizontal_chainStyle, com.thecrackertechnology.andrax.R.attr.layout_constraintHorizontal_weight, com.thecrackertechnology.andrax.R.attr.layout_constraintLeft_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintLeft_toLeftOf, com.thecrackertechnology.andrax.R.attr.layout_constraintLeft_toRightOf, com.thecrackertechnology.andrax.R.attr.layout_constraintRight_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintRight_toLeftOf, com.thecrackertechnology.andrax.R.attr.layout_constraintRight_toRightOf, com.thecrackertechnology.andrax.R.attr.layout_constraintStart_toEndOf, com.thecrackertechnology.andrax.R.attr.layout_constraintStart_toStartOf, com.thecrackertechnology.andrax.R.attr.layout_constraintTop_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintTop_toBottomOf, com.thecrackertechnology.andrax.R.attr.layout_constraintTop_toTopOf, com.thecrackertechnology.andrax.R.attr.layout_constraintVertical_bias, com.thecrackertechnology.andrax.R.attr.layout_constraintVertical_chainStyle, com.thecrackertechnology.andrax.R.attr.layout_constraintVertical_weight, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_default, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_max, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_min, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_percent, com.thecrackertechnology.andrax.R.attr.layout_editor_absoluteX, com.thecrackertechnology.andrax.R.attr.layout_editor_absoluteY, com.thecrackertechnology.andrax.R.attr.layout_goneMarginBottom, com.thecrackertechnology.andrax.R.attr.layout_goneMarginEnd, com.thecrackertechnology.andrax.R.attr.layout_goneMarginLeft, com.thecrackertechnology.andrax.R.attr.layout_goneMarginRight, com.thecrackertechnology.andrax.R.attr.layout_goneMarginStart, com.thecrackertechnology.andrax.R.attr.layout_goneMarginTop, com.thecrackertechnology.andrax.R.attr.layout_optimizationLevel};
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
        public static final int ConstraintLayout_Layout_barrierDirection = 6;
        public static final int ConstraintLayout_Layout_chainUseRtl = 7;
        public static final int ConstraintLayout_Layout_constraintSet = 8;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids = 9;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight = 10;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth = 11;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintCircle = 17;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 56;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 57;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 58;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 59;
        public static final int[] ConstraintLayout_placeholder = {com.thecrackertechnology.andrax.R.attr.content, com.thecrackertechnology.andrax.R.attr.emptyVisibility};
        public static final int ConstraintLayout_placeholder_content = 0;
        public static final int ConstraintLayout_placeholder_emptyVisibility = 1;
        public static final int[] ConstraintSet = {16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843039, 16843040, 16843071, 16843072, 16843551, 16843552, 16843553, 16843554, 16843555, 16843556, 16843557, 16843558, 16843559, 16843560, 16843701, 16843702, 16843770, 16843840, com.thecrackertechnology.andrax.R.attr.barrierAllowsGoneWidgets, com.thecrackertechnology.andrax.R.attr.barrierDirection, com.thecrackertechnology.andrax.R.attr.chainUseRtl, com.thecrackertechnology.andrax.R.attr.constraint_referenced_ids, com.thecrackertechnology.andrax.R.attr.layout_constrainedHeight, com.thecrackertechnology.andrax.R.attr.layout_constrainedWidth, com.thecrackertechnology.andrax.R.attr.layout_constraintBaseline_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintBaseline_toBaselineOf, com.thecrackertechnology.andrax.R.attr.layout_constraintBottom_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintBottom_toBottomOf, com.thecrackertechnology.andrax.R.attr.layout_constraintBottom_toTopOf, com.thecrackertechnology.andrax.R.attr.layout_constraintCircle, com.thecrackertechnology.andrax.R.attr.layout_constraintCircleAngle, com.thecrackertechnology.andrax.R.attr.layout_constraintCircleRadius, com.thecrackertechnology.andrax.R.attr.layout_constraintDimensionRatio, com.thecrackertechnology.andrax.R.attr.layout_constraintEnd_toEndOf, com.thecrackertechnology.andrax.R.attr.layout_constraintEnd_toStartOf, com.thecrackertechnology.andrax.R.attr.layout_constraintGuide_begin, com.thecrackertechnology.andrax.R.attr.layout_constraintGuide_end, com.thecrackertechnology.andrax.R.attr.layout_constraintGuide_percent, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_default, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_max, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_min, com.thecrackertechnology.andrax.R.attr.layout_constraintHeight_percent, com.thecrackertechnology.andrax.R.attr.layout_constraintHorizontal_bias, com.thecrackertechnology.andrax.R.attr.layout_constraintHorizontal_chainStyle, com.thecrackertechnology.andrax.R.attr.layout_constraintHorizontal_weight, com.thecrackertechnology.andrax.R.attr.layout_constraintLeft_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintLeft_toLeftOf, com.thecrackertechnology.andrax.R.attr.layout_constraintLeft_toRightOf, com.thecrackertechnology.andrax.R.attr.layout_constraintRight_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintRight_toLeftOf, com.thecrackertechnology.andrax.R.attr.layout_constraintRight_toRightOf, com.thecrackertechnology.andrax.R.attr.layout_constraintStart_toEndOf, com.thecrackertechnology.andrax.R.attr.layout_constraintStart_toStartOf, com.thecrackertechnology.andrax.R.attr.layout_constraintTop_creator, com.thecrackertechnology.andrax.R.attr.layout_constraintTop_toBottomOf, com.thecrackertechnology.andrax.R.attr.layout_constraintTop_toTopOf, com.thecrackertechnology.andrax.R.attr.layout_constraintVertical_bias, com.thecrackertechnology.andrax.R.attr.layout_constraintVertical_chainStyle, com.thecrackertechnology.andrax.R.attr.layout_constraintVertical_weight, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_default, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_max, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_min, com.thecrackertechnology.andrax.R.attr.layout_constraintWidth_percent, com.thecrackertechnology.andrax.R.attr.layout_editor_absoluteX, com.thecrackertechnology.andrax.R.attr.layout_editor_absoluteY, com.thecrackertechnology.andrax.R.attr.layout_goneMarginBottom, com.thecrackertechnology.andrax.R.attr.layout_goneMarginEnd, com.thecrackertechnology.andrax.R.attr.layout_goneMarginLeft, com.thecrackertechnology.andrax.R.attr.layout_goneMarginRight, com.thecrackertechnology.andrax.R.attr.layout_goneMarginStart, com.thecrackertechnology.andrax.R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_alpha = 13;
        public static final int ConstraintSet_android_elevation = 26;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 24;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 23;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_maxHeight = 10;
        public static final int ConstraintSet_android_maxWidth = 9;
        public static final int ConstraintSet_android_minHeight = 12;
        public static final int ConstraintSet_android_minWidth = 11;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotation = 20;
        public static final int ConstraintSet_android_rotationX = 21;
        public static final int ConstraintSet_android_rotationY = 22;
        public static final int ConstraintSet_android_scaleX = 18;
        public static final int ConstraintSet_android_scaleY = 19;
        public static final int ConstraintSet_android_transformPivotX = 14;
        public static final int ConstraintSet_android_transformPivotY = 15;
        public static final int ConstraintSet_android_translationX = 16;
        public static final int ConstraintSet_android_translationY = 17;
        public static final int ConstraintSet_android_translationZ = 25;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_barrierAllowsGoneWidgets = 27;
        public static final int ConstraintSet_barrierDirection = 28;
        public static final int ConstraintSet_chainUseRtl = 29;
        public static final int ConstraintSet_constraint_referenced_ids = 30;
        public static final int ConstraintSet_layout_constrainedHeight = 31;
        public static final int ConstraintSet_layout_constrainedWidth = 32;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 33;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 34;
        public static final int ConstraintSet_layout_constraintBottom_creator = 35;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 36;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 37;
        public static final int ConstraintSet_layout_constraintCircle = 38;
        public static final int ConstraintSet_layout_constraintCircleAngle = 39;
        public static final int ConstraintSet_layout_constraintCircleRadius = 40;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 41;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 42;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 43;
        public static final int ConstraintSet_layout_constraintGuide_begin = 44;
        public static final int ConstraintSet_layout_constraintGuide_end = 45;
        public static final int ConstraintSet_layout_constraintGuide_percent = 46;
        public static final int ConstraintSet_layout_constraintHeight_default = 47;
        public static final int ConstraintSet_layout_constraintHeight_max = 48;
        public static final int ConstraintSet_layout_constraintHeight_min = 49;
        public static final int ConstraintSet_layout_constraintHeight_percent = 50;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 51;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 52;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 53;
        public static final int ConstraintSet_layout_constraintLeft_creator = 54;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 55;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 56;
        public static final int ConstraintSet_layout_constraintRight_creator = 57;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 58;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 59;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 60;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 61;
        public static final int ConstraintSet_layout_constraintTop_creator = 62;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 63;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 64;
        public static final int ConstraintSet_layout_constraintVertical_bias = 65;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 66;
        public static final int ConstraintSet_layout_constraintVertical_weight = 67;
        public static final int ConstraintSet_layout_constraintWidth_default = 68;
        public static final int ConstraintSet_layout_constraintWidth_max = 69;
        public static final int ConstraintSet_layout_constraintWidth_min = 70;
        public static final int ConstraintSet_layout_constraintWidth_percent = 71;
        public static final int ConstraintSet_layout_editor_absoluteX = 72;
        public static final int ConstraintSet_layout_editor_absoluteY = 73;
        public static final int ConstraintSet_layout_goneMarginBottom = 74;
        public static final int ConstraintSet_layout_goneMarginEnd = 75;
        public static final int ConstraintSet_layout_goneMarginLeft = 76;
        public static final int ConstraintSet_layout_goneMarginRight = 77;
        public static final int ConstraintSet_layout_goneMarginStart = 78;
        public static final int ConstraintSet_layout_goneMarginTop = 79;
        public static final int[] LinearConstraintLayout = {16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;

        private styleable() {
        }
    }
}
